plugins:
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.3.6
  SuggestExtensions: false

  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "config/initializers/**"
    - "app/models/**"

Rails:
  Enabled: true

RSpec:
  Enabled: true
